@startuml
'Modelの設計
class Task{
    - int ordinalNumber
    - String title
    - String entryDate

    + Task(ordinalNumber:int, title: String, entryDate: String)
}

class VueToDoList{
    - String title
    - Task[] taskList
    - int taskCreateCount= 0

    + VueToDoList()
    + addTask(title: String)
    + canAddTask(): boolean
    + deleteTask(ordinalNumber: int): void
    + getEntryDate(): String
}

@enduml